<div class="modal fade" id="nonCashPaymentModal" tabindex="-1" aria-labelledby="nonCashPaymentModalTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content border-0 rounded-4 shadow">
<div class="modal-header text-white border-0" style="background:linear-gradient(135deg,#0d6efd,#0a58ca)"><div><h5 class="modal-title fw-bold" id="nonCashPaymentModalTitle">Add Non-Cash Payment</h5><small class="text-white-50">Enter payment details</small></div><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button></div>
<div class="modal-body p-4"><form id="non_cash_payment_form" novalidate><input type="hidden" id="non_cash_payment_id" value="0">
<div class="mb-3"><label class="form-label fw-semibold" for="non_cash_payment_type">Payment Type</label><select class="form-select" id="non_cash_payment_type" required><option value="">Select payment type</option><option value="limitless">Limitless Payment</option><option value="credit_debit">Credit / Debit</option><option value="gcash">GCash</option><option value="check">Check</option></select></div>
<div class="mb-3"><label class="form-label fw-semibold" for="non_cash_payment_amount">Amount</label><div class="input-group"><span class="input-group-text">₱</span><input type="number" class="form-control" id="non_cash_payment_amount" min="0" step="0.01" required></div></div>
<div class="mb-3"><label class="form-label fw-semibold" for="non_cash_payment_name">Name</label><input type="text" class="form-control" id="non_cash_payment_name" required></div>
<div class="mb-3"><label class="form-label fw-semibold" for="non_cash_payment_number">Number</label><input type="text" class="form-control" id="non_cash_payment_number" required></div>
<div><label class="form-label fw-semibold" for="non_cash_payment_reference">Reference Number</label><input type="text" class="form-control" id="non_cash_payment_reference" required></div></form></div>
<div class="modal-footer border-0 bg-light"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary px-4" id="save_non_cash_payment"><i class="bi bi-save me-2"></i><span>Save Payment</span></button></div>
</div></div></div>
<div class="modal fade" id="deleteNonCashPaymentModal" tabindex="-1" aria-labelledby="deleteNonCashPaymentTitle" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-sm"><div class="modal-content border-0 rounded-4 shadow"><div class="modal-header border-0"><h5 class="modal-title fw-bold" id="deleteNonCashPaymentTitle">Delete Payment?</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body">Delete this non-cash payment record?</div><div class="modal-footer border-0"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button type="button" class="btn btn-danger" id="confirm_delete_non_cash_payment">Delete</button></div></div></div></div>